project_id = "dlhkvzslowervdyzideq"

[functions.generate_blurb]
verify_jwt = false

[functions.scrape_ica]
verify_jwt = false

[functions.scrape_bfi]
verify_jwt = false

[functions.scrape_all]
verify_jwt = false

[functions.scrape_screenings]
verify_jwt = false
